package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.Transaction;

import java.util.List;

public class UserDaoHibernateImpl implements UserDao {
    public UserDaoHibernateImpl() {

    }


    @Override
    public void createUsersTable() {

        Session session = Util.getSessionFactory().getCurrentSession();

        Transaction tx = session.beginTransaction();
        SQLQuery query = session.createNativeQuery("CREATE TABLE IF NOT EXISTS users"
                + "  (id              INTEGER generated by default as identity,"
                + "   name            VARCHAR(256),"
                + "   lastName        VARCHAR(256),"
                + "   age             INTEGER)");
        query.executeUpdate();

    }

    @Override
    public void dropUsersTable() {

    }

    @Override
    public void saveUser(String name, String lastName, byte age) {

    }

    @Override
    public void removeUserById(long id) {

    }

    @Override
    public List<User> getAllUsers() {
            try (Session session = Util.getSessionFactory().openSession()) {
                return session.createQuery("from User", User.class).list();
            }
    }

    @Override
    public void cleanUsersTable() {

    }
}
